- hosts: thea_node
  gather_facts: False
  become: yes
  vars:
    local_db: "/home/ubuntu/.local/share/polkadex-stencil/chains/polkadex_testnet/db"
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
    - name: Make sure service is stopped
      systemd:
        name: polkadex-stencil
        state: stopped
    - name: Delete Polkadex Thea Node's DB
      file:
        path: "{{ local_db }}"
        state: absent
    - name: Delete Polkadex Binary
      file:
        path: /usr/local/bin/polkadex-stencil
        state: absent
    - name: Delete Polkadex CustomSpec
      file:
        path: /etc/customSpecRaw.json
        state: absent
    - name: Download polkadex-thea-node chainspec
      get_url:
        url: https://polkadex-thea.s3.ap-south-1.amazonaws.com/customSpecRaw.json
        dest: /etc/customSpecRaw.json

    - name: Download polkadex-thea-node
      get_url:
        url: https://polkadex-thea.s3.ap-south-1.amazonaws.com/polkadex-stencil
        dest: /usr/local/bin/polkadex-stencil
        mode: "0755"

    - name: Make sure service is running
      systemd:
        name: polkadex-stencil
        state: started
        enabled: yes

    - name: Pause for 30 seconds
      pause:
        seconds: 30
    - name: Set Babe Keys
      shell:
        "curl http://localhost:9945 -H \"Content-Type:application/json;charset=utf-8\" -d \"@/home/ubuntu/{{ inventory_hostname }}-babe.json\" "
      register: aura_output

    - name: Print Aura RPC output
      debug:
        var: aura_output

    - name: Set Grandpa Keys
      shell:
        "curl http://localhost:9945 -H \"Content-Type:application/json;charset=utf-8\" -d \"@/home/ubuntu/{{ inventory_hostname }}-gran.json\" "
      register: gran_output

    - name: Printing Grandpa RPC Output
      debug:
        var: gran_output

    - name: Set Grandpa Keys
      shell:
        "curl http://localhost:9945 -H \"Content-Type:application/json;charset=utf-8\" -d \"@/home/ubuntu/{{ inventory_hostname }}-gran.json\" "
      register: gran_output

    - name: Printing Grandpa RPC Output
      debug:
        var: gran_output

    - name: Set IAM Online Keys
      shell:
        "curl http://localhost:9945 -H \"Content-Type:application/json;charset=utf-8\" -d \"@/home/ubuntu/{{ inventory_hostname }}-imon.json\" "
      register: imon_output

    - name: Printing Grandpa RPC Output
      debug:
        var: imon_output

    - name: Set Audi Keys
      shell:
        "curl http://localhost:9945 -H \"Content-Type:application/json;charset=utf-8\" -d \"@/home/ubuntu/{{ inventory_hostname }}-audi.json\" "
      register: audi_output

    - name: Printing Audi RPC Output
      debug:
        var: audi_output

    - name: Set Thea Keys
      shell:
         "curl http://localhost:9945 -H \"Content-Type:application/json;charset=utf-8\" -d \"@/home/ubuntu/{{ inventory_hostname }}-thea.json\" "
      register: thea_output

    - name: Printing Thea RPC Output
      debug:
        var: thea_output

    - name: Restart polkadex-thea-node
      systemd:
        name: polkadex-stencil
        state: restarted
        daemon_reload: yes
      register: restart_log

    - name: Restart Logs
      debug:
        var: restart_log
