- hosts: thea_node
  order: sorted
  become: yes
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
    - name: Copy Babe Keys
      template:
        src: "templates/{{ inventory_hostname}}-babe.json"
        dest: "/home/ubuntu/{{ inventory_hostname }}-babe.json"
        owner: ubuntu
        group: ubuntu
    - name: Copy Grandpa Keys
      template:
        src: "templates/{{ inventory_hostname}}-gran.json"
        dest: "/home/ubuntu/{{ inventory_hostname }}-gran.json"
        owner: ubuntu
        group: ubuntu
    - name: Copy IAM Online Keys
      template:
        src: "templates/{{ inventory_hostname}}-imon.json"
        dest: "/home/ubuntu/{{ inventory_hostname }}-imon.json"
        owner: ubuntu
        group: ubuntu
    - name: Copy AUTH Discovery Keys
      template:
        src: "templates/{{ inventory_hostname}}-audi.json"
        dest: "/home/ubuntu/{{ inventory_hostname }}-audi.json"
        owner: ubuntu
        group: ubuntu
    - name: Copy Thea Keys
      template:
        src: "templates/{{ inventory_hostname}}-thea.json"
        dest: "/home/ubuntu/{{ inventory_hostname }}-thea.json"
        owner: ubuntu
        group: ubuntu
    - name: Set Babe Keys
      shell:
        "curl http://localhost:9945 -H \"Content-Type:application/json;charset=utf-8\" -d \"@/home/ubuntu/{{ inventory_hostname }}-babe.json\" "
      register: aura_output

    - name: Print Aura RPC output
      debug:
        var: aura_output

    - name: Set Grandpa Keys
      shell:
        "curl http://localhost:9945 -H \"Content-Type:application/json;charset=utf-8\" -d \"@/home/ubuntu/{{ inventory_hostname }}-gran.json\" "
      register: gran_output

    - name: Printing Grandpa RPC Output
      debug:
        var: gran_output

    - name: Set IAM Online Keys
      shell:
        "curl http://localhost:9945 -H \"Content-Type:application/json;charset=utf-8\" -d \"@/home/ubuntu/{{ inventory_hostname }}-imon.json\" "
      register: imon_output

    - name: Printing Grandpa RPC Output
      debug:
        var: imon_output

    - name: Set Audi Keys
      shell:
        "curl http://localhost:9945 -H \"Content-Type:application/json;charset=utf-8\" -d \"@/home/ubuntu/{{ inventory_hostname }}-audi.json\" "
      register: audi_output

    - name: Printing Audi RPC Output
      debug:
        var: audi_output

    - name: Set Thea Keys
      shell:
        "curl http://localhost:9945 -H \"Content-Type:application/json;charset=utf-8\" -d \"@/home/ubuntu/{{ inventory_hostname }}-thea.json\" "
      register: thea_output

    - name: Printing Thea RPC Output
      debug:
        var: thea_output

    - name: Restart polkadex-thea-node
      systemd:
        name: polkadex-stencil
        state: restarted
        daemon_reload: yes
      register: restart_log

    - name: Restart Logs
      debug:
        var: restart_log